#!/bin/bash -e

# fah-client-bastet postinstall

SCRIPTS="$(dirname "$0")"

# Setup run directory
RUN_DIR="/Library/Application Support/FAHClient"
if [ ! -d "$RUN_DIR" ]; then mkdir -p "$RUN_DIR"; fi
chmod -R u+rwX,go-w "$RUN_DIR"
chown -R nobody:nobody "$RUN_DIR"

PLIST=/Library/LaunchDaemons/org.foldingathome.fahclient.plist

"$SCRIPTS"/organize-credits.sh &

# Start service
chmod 0644 "$PLIST"
launchctl load -w "$PLIST"

# start, in case RunAtLoad is false
launchctl start org.foldingathome.fahclient || true

# Don't launch GUI if CLI install
[ "$COMMAND_LINE_INSTALL" == "1" ] && exit 0

SUDO=""
if [ "$SUDO_USER" != "" ]; then
  SUDO="sudo -u $SUDO_USER"
elif [ "$USER" != "" ]; then
  SUDO="sudo -u $USER"
fi

# this won't work in onquit
# the temp pkg with scripts gets deleted when this script exits
BROWSER=$($SUDO "$SCRIPTS"/defaultbrowser.sh) || BROWSER=""
# partial url decode, just the %nn
# https://stackoverflow.com/a/70560850
: "${BROWSER}"; printf -v BROWSER '%b' "${_//%/\\x}"

export SUDO BROWSER
"$SCRIPTS"/onquit &
