#!/bin/bash -e

# fah-client-bastet postinstall

# Setup run directory
RUN_DIR="/Library/Application Support/FAHClient"
if [ ! -d "$RUN_DIR" ]; then mkdir -p "$RUN_DIR"; fi
chmod -R u+rwX,go-w "$RUN_DIR"
chown -R nobody:nobody "$RUN_DIR"

PLIST=/Library/LaunchDaemons/org.foldingathome.fahclient.plist

# Start service
chmod 0644 "$PLIST"
launchctl load -w "$PLIST"

# start, in case RunAtLoad is false
launchctl start org.foldingathome.fahclient || true

# Don't launch GUI if CLI install
[ "$COMMAND_LINE_INSTALL" == "1" ] && exit 0

# open in user's default web browser
SUDO=""
if [ "$SUDO_USER" != "" ]; then
  SUDO="sudo -u $SUDO_USER"
elif [ "$USER" != "" ]; then
  SUDO="sudo -u $USER"
fi
SCRIPTS="$(dirname "$0")"
"$SCRIPTS"/onquit $SUDO open https://app.foldingathome.org/
