#!/bin/bash -e

# fah-client-bastet preinstall

# Unload any launchd jobs
OLD_LAUNCHD="/Library/LaunchDaemons/FAHClient.plist"
OLD_LAUNCHD2="/Library/LaunchDaemons/edu.stanford.folding.fahclient.plist"
NEW_LAUNCHD="/Library/LaunchDaemons/org.foldingathome.fahclient.plist"
AGENT_PLIST="/Library/LaunchAgents/org.foldingathome.fah-screen-agent.plist"

if [ -f "$NEW_LAUNCHD" ]; then
    launchctl unload -w "$NEW_LAUNCHD" || true
fi
if [ -f "$OLD_LAUNCHD2" ]; then
    launchctl unload -w "$OLD_LAUNCHD2" || true
    rm -f "$OLD_LAUNCHD2" || true
fi
if [ -f "$OLD_LAUNCHD" ]; then
    launchctl unload -w "$OLD_LAUNCHD" || true
    rm -f "$OLD_LAUNCHD" || true
fi

if [ -f "$AGENT_PLIST" ]; then
  # stop agent running in console user's session and unload job
  conuser=$(/usr/bin/stat -f "%Su" /dev/console) || conuser="root"
  conuid=$(/usr/bin/id -u "$conuser") || conuid=0
  if [[ $conuid != 0 ]]; then
    launchctl bootout gui/$conuid "$AGENT_PLIST" || true
  fi
fi

# Assuming upgrade, remove old stuff
F1="/Applications/FAHClient.url"
F2="/Applications/Folding@home/Web Control.url"
F3="/Library/Application Support/FAHClient/GPUs.txt"
F4="/Applications/Folding@home/Uninstall Folding@home.pkg"
F5="/Applications/Folding@home/fahclient.url"
[ -f "$F1" ] && rm -f "$F1" || true
[ -f "$F2" ] && rm -f "$F2" || true
[ -f "$F3" ] && rm -f "$F3" || true
[ -f "$F4" ] && rm -f "$F4" || true
[ -f "$F5" ] && rm -f "$F5" || true
A1="/Applications/Folding@home/FAHControl.app"
A2="/Applications/Folding@home/FAHViewer.app"
[ -d "$A1" ] && rm -rf "$A1" || true
[ -d "$A2" ] && rm -rf "$A2" || true
