#!/bin/sh -e

. /usr/share/debconf/confmodule

CONFIG=/etc/fahclient/config.xml
PRIORITY=critical

if [ "$1" = "configure" -o "$1" = "reconfigure" ]; then
    if [ ! -e $CONFIG ]; then
        # Ask questions
        db_input $PRIORITY fahclient/user || true
        db_input $PRIORITY fahclient/team || true
        db_input $PRIORITY fahclient/passkey || true
        db_input $PRIORITY fahclient/power || true
    fi

    db_input $PRIORITY fahclient/autostart || true
    db_go || true
fi
