#!/bin/sh -e

NAME=fah-client

case "$1" in
  upgrade)
    ACTIVE=$(systemctl is-active $NAME || true)

    if [ "$ACTIVE" = "active" ]; then
      # Stop the service
      service $NAME stop
    fi
    ;;
esac
